---
- name: Install Latest Blender from Official Tarball
  hosts: all
  become: yes
  
  tasks:
    - name: Download the latest Blender tarball
      ansible.builtin.get_url:
        url: "https://download.blender.org/release/Blender4.5/blender-4.5.3-linux-x64.tar.xz"
        dest: "/tmp/blender-latest.tar.xz"
        mode: '0644'
    
    - name: Ensure /opt/blender directory exists
      ansible.builtin.file:
        path: "/opt/blender"
        state: directory
        mode: '0755'
    
    - name: Unarchive the Blender tarball to /opt/blender
      ansible.builtin.unarchive:
        src: "/tmp/blender-latest.tar.xz"
        dest: "/opt/blender"
        remote_src: yes
    
    - name: Create a symbolic link to the blender executable
      ansible.builtin.file:
        src: "/opt/blender/blender-4.5.3-linux-x64/blender"
        dest: "/usr/local/bin/blender"
        state: link
        force: yes
    
    - name: Clean up the downloaded tarball
      ansible.builtin.file:
        path: "/tmp/blender-latest.tar.xz"
        state: absent
