---
- name: Install Brave Browser on AlmaLinux and Ubuntu
  hosts: all
  become: yes
  
  tasks:
    - name: Install required DNF plugins on RedHat-based systems
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present
      when: ansible_os_family == "RedHat"
    
    - name: Add Brave repository on RedHat-based systems
      ansible.builtin.shell: |
        dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
      when: ansible_os_family == "RedHat"
    
    - name: Install Brave Browser on RedHat-based systems
      ansible.builtin.dnf:
        name: brave-browser
        state: present
        update_cache: yes
      when: ansible_os_family == "RedHat"
      
    - name: Add Brave repository on Debian-based systems
      ansible.builtin.apt_repository:
        repo: 'deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main'
        state: present
      when: ansible_os_family == "Debian"
    
    - name: Import Brave GPG key on Debian-based systems
      ansible.builtin.get_url:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
        mode: '0644'
      when: ansible_os_family == "Debian"
      
    - name: Install Brave Browser on Debian-based systems
      ansible.builtin.apt:
        name: brave-browser
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
