---
- name: Remove Slack from AlmaLinux and Ubuntu
  hosts: all
  become: yes

  tasks:
    - name: Remove Slack package from RedHat-based systems
      ansible.builtin.dnf:
        name: slack-desktop
        state: absent
      when: ansible_os_family == "RedHat"

    - name: Remove Slack repository file on RedHat-based systems
      ansible.builtin.file:
        path: /etc/yum.repos.d/slack-desktop.repo
        state: absent
      when: ansible_os_family == "RedHat"

    - name: Remove Slack package from Debian-based systems
      ansible.builtin.apt:
        name: slack-desktop
        state: absent
        autoremove: yes
        purge: yes
      when: ansible_os_family == "Debian"

    - name: Remove Brave repository from Debian-based systems
      ansible.builtin.apt_repository:
        repo: 'deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main'
        state: absent
      when: ansible_os_family == "Debian"
