---
- name: Deploy NOX wallpaper for AD users
  hosts: all
  become: yes
  vars:
    wallpaper_source: "NOX_Wallpaper.jpg"  # File in your playbook's files/ directory
    wallpaper_system_path: "/usr/share/backgrounds/nox-wallpaper.jpg"
    domain_name: "ad.noxvfx.com"

  tasks:
    - name: Copy NOX wallpaper to system backgrounds directory
      ansible.builtin.copy:
        src: "{{ wallpaper_source }}"
        dest: "{{ wallpaper_system_path }}"
        mode: '0644'
        owner: root
        group: root

    - name: Create dconf system database directory
      ansible.builtin.file:
        path: /etc/dconf/db/local.d
        state: directory
        mode: '0755'

    - name: Create dconf profile for users
      ansible.builtin.copy:
        content: |
          user-db:user
          system-db:local
        dest: /etc/dconf/profile/user
        mode: '0644'

    - name: Set system-wide wallpaper via dconf
      ansible.builtin.copy:
        content: |
          # NOX Company Wallpaper Settings
          [org/gnome/desktop/background]
          picture-uri='file://{{ wallpaper_system_path }}'
          picture-uri-dark='file://{{ wallpaper_system_path }}'
          picture-options='zoom'
          primary-color='#2e3436'
          secondary-color='#2e3436'
          
          [org/gnome/desktop/screensaver]
          picture-uri='file://{{ wallpaper_system_path }}'
          picture-options='zoom'
        dest: /etc/dconf/db/local.d/01-nox-wallpaper
        mode: '0644'
      notify: update dconf

    - name: Create wallpaper script for user sessions
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          # NOX Wallpaper setter for AD users
          
          # Wait for GNOME session to be fully loaded
          sleep 10
          
          # Ensure we have a display and session bus
          if [ -z "$DISPLAY" ]; then
              export DISPLAY=:0
          fi
          
          if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
              export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u)/bus"
          fi
          
          # Wait for gsettings to be available
          timeout=30
          while [ $timeout -gt 0 ]; do
              if gsettings list-schemas | grep -q "org.gnome.desktop.background"; then
                  break
              fi
              sleep 1
              ((timeout--))
          done
          
          # Set wallpaper using gsettings
          if gsettings list-schemas | grep -q "org.gnome.desktop.background"; then
              gsettings set org.gnome.desktop.background picture-uri "file://{{ wallpaper_system_path }}"
              gsettings set org.gnome.desktop.background picture-uri-dark "file://{{ wallpaper_system_path }}"
              gsettings set org.gnome.desktop.background picture-options 'zoom'
              
              # Also set screensaver
              gsettings set org.gnome.desktop.screensaver picture-uri "file://{{ wallpaper_system_path }}"
              
              # Log success
              logger "NOX wallpaper set for user $(whoami) on $(hostname)"
          else
              logger "Failed to set NOX wallpaper for user $(whoami) - gsettings not available"
          fi
        dest: /usr/local/bin/set-nox-wallpaper.sh
        mode: '0755'

    - name: Create system-wide autostart directory
      ansible.builtin.file:
        path: /etc/xdg/autostart
        state: directory
        mode: '0755'

    - name: Create autostart desktop entry for wallpaper
      ansible.builtin.copy:
        content: |
          [Desktop Entry]
          Type=Application
          Name=NOX Wallpaper
          Comment=Set NOX company wallpaper
          Exec=/usr/local/bin/set-nox-wallpaper.sh
          Hidden=false
          NoDisplay=true
          X-GNOME-Autostart-enabled=true
          X-GNOME-Autostart-Delay=15
          Categories=System;Settings;
          StartupNotify=false
        dest: /etc/xdg/autostart/nox-wallpaper.desktop
        mode: '0644'

    - name: Add wallpaper script to system profile
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          # Set NOX wallpaper for GNOME sessions
          if [ "$XDG_CURRENT_DESKTOP" = "GNOME" ] && [ -n "$DISPLAY" ]; then
              # Run in background to not delay login
              (/usr/local/bin/set-nox-wallpaper.sh &) 2>/dev/null
          fi
        dest: /etc/profile.d/Z99-nox-wallpaper.sh
        mode: '0755'

    - name: Create GDM (login screen) wallpaper configuration
      ansible.builtin.copy:
        content: |
          [org/gnome/desktop/background]
          picture-uri='file://{{ wallpaper_system_path }}'
          picture-options='zoom'
          primary-color='#2e3436'
          
          [org/gnome/login-screen]
          logo='file://{{ wallpaper_system_path }}'
        dest: /etc/dconf/db/gdm.d/01-nox-wallpaper
        mode: '0644'
      notify: update dconf

    - name: Test if any users are currently logged into GNOME
      ansible.builtin.shell: |
        # Check for active GNOME sessions
        ps aux | grep -v grep | grep gnome-session | awk '{print $1}' | sort | uniq
      register: active_gnome_users
      changed_when: false
      failed_when: false

    - name: Set wallpaper for currently logged-in users
      ansible.builtin.shell: |
        for user in {{ active_gnome_users.stdout_lines | join(' ') }}; do
          if [ -n "$user" ] && [ "$user" != "gdm" ]; then
            user_id=$(id -u "$user" 2>/dev/null)
            if [ -n "$user_id" ] && [ -S "/run/user/$user_id/bus" ]; then
              echo "Setting wallpaper for logged-in user: $user"
              sudo -u "$user" DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$user_id/bus" \
                gsettings set org.gnome.desktop.background picture-uri "file://{{ wallpaper_system_path }}" 2>/dev/null || true
              sudo -u "$user" DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$user_id/bus" \
                gsettings set org.gnome.desktop.background picture-uri-dark "file://{{ wallpaper_system_path }}" 2>/dev/null || true
            fi
          fi
        done
      when: active_gnome_users.stdout_lines | length > 0
      ignore_errors: yes

    - name: Verify wallpaper file permissions and SELinux context
      ansible.builtin.file:
        path: "{{ wallpaper_system_path }}"
        mode: '0644'
        setype: usr_t
      ignore_errors: yes

    - name: Display setup completion message
      ansible.builtin.debug:
        msg: |
          NOX wallpaper deployment completed!
          
          Wallpaper location: {{ wallpaper_system_path }}
          
          The wallpaper will be applied:
          1. Immediately for currently logged-in users
          2. At next login for all AD users via autostart
          3. Via system profile for all GNOME sessions
          4. On the GDM login screen
          
          Users may need to log out and back in to see the wallpaper.

  handlers:
    - name: update dconf
      ansible.builtin.command: dconf update
      changed_when: true
