---
- name: Deploy wallpaper (simple approach)
  hosts: all
  become: yes
  vars:
    wallpaper_source: "NOX_Wallpaper.jpg"
  
  tasks:
    - name: Get regular users
      ansible.builtin.shell: "awk -F: '$3 >= 1000 && $3 < 60000 {print $1}' /etc/passwd"
      register: users
      changed_when: false

    - name: Copy wallpaper to each user's home
      ansible.builtin.copy:
        src: "{{ wallpaper_source }}"
        dest: "/home/{{ item }}/wallpaper.jpg"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: '0644'
      loop: "{{ users.stdout_lines }}"

    - name: Add wallpaper command to user's .bashrc
      ansible.builtin.lineinfile:
        path: "/home/{{ item }}/.bashrc"
        line: |
          # Set wallpaper if in GNOME session
          if [ "$XDG_CURRENT_DESKTOP" = "GNOME" ] && [ -n "$DISPLAY" ]; then
              gsettings set org.gnome.desktop.background picture-uri "file:///home/{{ item }}/wallpaper.jpg" 2>/dev/null || true
          fi
        owner: "{{ item }}"
        group: "{{ item }}"
        create: yes
      loop: "{{ users.stdout_lines }}"
