---
- name: Configure GDM settings
  hosts: all
  become: yes
  tasks:
    - name: Configure GDM to use X11 (no auto-login)
      copy:
        dest: /etc/gdm/custom.conf
        content: |
          [daemon]
          WaylandEnable=false
          DefaultSession=gnome-xorg.desktop
        mode: '0644'
