---
- name: Install DasElement Lite on AlmaLinux 9.6
  hosts: all
  become: yes
  
  vars:
    # DasElement Lite version (NOT full das-element)
    daselement_lite_version: "2.1.4"
    daselement_package_name: "das-element-lite"
    daselement_rpm_file: "{{ daselement_package_name }}_{{ daselement_lite_version }}_lin.rpm"
    daselement_rpm_path: "../../files/{{ daselement_rpm_file }}"
    daselement_install_path: "/opt/{{ daselement_package_name }}-{{ daselement_lite_version }}"
    
    # Environment variables
    daselement_license_server: "5053@license"
    daselement_config_path: "/mnt/Library/_daselement/das-element.conf"
    daselement_resources_path: "/mnt/Library/_daselement/resources"
    
  tasks:
    - name: Install libXScrnSaver dependency
      ansible.builtin.yum:
        name: libXScrnSaver
        state: present
        
    - name: Copy DasElement Lite RPM to target machine
      ansible.builtin.copy:
        src: "{{ daselement_rpm_path }}"
        dest: "/tmp/{{ daselement_rpm_file }}"
        mode: '0644'
        
    - name: Install DasElement Lite RPM
      ansible.builtin.yum:
        name: "/tmp/{{ daselement_rpm_file }}"
        state: present
        disable_gpg_check: yes
        
    - name: Clean up temporary RPM file
      ansible.builtin.file:
        path: "/tmp/{{ daselement_rpm_file }}"
        state: absent
        
    - name: Get list of home directories for real users
      ansible.builtin.shell: |
        getent passwd | awk -F: '$3 >= 1000 && $3 < 65534 {print $6}'
      register: user_home_dirs
      changed_when: false
      
    - name: Overwrite variables.env file with environment variables for all users
      ansible.builtin.copy:
        dest: "{{ item }}/.das-element/variables.env"
        owner: "{{ item.split('/')[-1] }}"
        mode: '0644'
        force: yes
        content: |
          #### point to the license server
          DASELEMENT_LICENSE={{ daselement_license_server }}
          
          #### path to the config file (.conf)
          DASELEMENT_CONFIG_PATH={{ daselement_config_path }}
          
          #### path to the resources folder, for presets, hooks, etc.
          DASELEMENT_RESOURCES={{ daselement_resources_path }}
      loop: "{{ user_home_dirs.stdout_lines }}"
      when: user_home_dirs.stdout_lines | length > 0
