---
- name: Install DaVinci Resolve Studio 20.2.1 with Centralized Database
  hosts: all
  become: yes
  
  vars:
    resolve_installer: "../../files/DaVinci_Resolve_Studio_20.2.1_Linux.run"
    resolve_temp_dir: "/tmp/resolve_install"
    resolve_projects_path: "/mnt/Projects/_resolve/projects"
    # Centralized PostgreSQL Database
    db_host: "192.168.11.128"
    db_port: "5432"
    db_name: "resolve_db"
    db_user: "resolve_user"
    db_password: "resolvedb"
    
  tasks:
    # STEP 1: Install System Dependencies
    - name: Enable CRB repository (CodeReady Builder)
      ansible.builtin.command: dnf config-manager --set-enabled crb
      args:
        creates: /etc/yum.repos.d/almalinux-crb.repo
    
    - name: Install EPEL repository
      ansible.builtin.dnf:
        name: epel-release
        state: present
    
    - name: Install required system dependencies
      ansible.builtin.dnf:
        name:
          - apr
          - apr-util
          - libxcb
          - xcb-util
          - xcb-util-wm
          - xcb-util-image
          - xcb-util-keysyms
          - xcb-util-renderutil
          - xcb-util-cursor
          - libxkbcommon
          - libxkbcommon-x11
          - libXrandr
          - libXinerama
          - libXcursor
          - mesa-libGLU
          - libglvnd-glx
          - libglvnd-egl
          - libglvnd-opengl
          - ocl-icd
          - opencl-headers
          - libxcrypt-compat
          - alsa-lib
          - pulseaudio-libs
          - unzip
          - postgresql
        state: present

    - name: Install SELinux policy tools
      ansible.builtin.dnf:
        name:
          - policycoreutils-python-utils
          - setroubleshoot-server
        state: present

    # STEP 2: Install DaVinci Resolve
    - name: Create temporary directory for installation
      ansible.builtin.file:
        path: "{{ resolve_temp_dir }}"
        state: directory
        mode: '0755'
    
    - name: Copy DaVinci Resolve installer to target
      ansible.builtin.copy:
        src: "{{ resolve_installer }}"
        dest: "{{ resolve_temp_dir }}/DaVinci_Resolve_Studio_20.2.1_Linux.run"
        mode: '0755'
    
    - name: Install DaVinci Resolve in silent mode as root
      ansible.builtin.command:
        cmd: "{{ resolve_temp_dir }}/DaVinci_Resolve_Studio_20.2.1_Linux.run -i -a -y"
      args:
        creates: /opt/resolve/bin/resolve
    
    - name: Verify DaVinci Resolve installation
      ansible.builtin.stat:
        path: /opt/resolve/bin/resolve
      register: resolve_binary
      failed_when: not resolve_binary.stat.exists

    - name: Kill any DaVinci Resolve processes started by installer
      ansible.builtin.shell: pkill -f "resolve" || true
      ignore_errors: yes

    # SELinux Configuration
    - name: Set SELinux context for DaVinci Resolve binaries
      ansible.builtin.command:
        cmd: restorecon -Rv /opt/resolve
      ignore_errors: yes

    - name: Allow DaVinci Resolve SELinux permissions
      ansible.builtin.command:
        cmd: setsebool -P {{ item }} 1
      loop:
        - allow_execmem
      ignore_errors: yes

    # STEP 3: Configure Centralized Database Connection
    - name: Create shared Resolve projects directory
      ansible.builtin.file:
        path: "{{ resolve_projects_path }}"
        state: directory
        mode: '0777'
        owner: root
        group: root

    - name: Create Resolve configuration directory in /etc/skel
      ansible.builtin.file:
        path: /etc/skel/.local/share/DaVinciResolve/configs
        state: directory
        mode: '0755'

    - name: Create .pgpass file in /etc/skel for automatic authentication
      ansible.builtin.copy:
        content: "{{ db_host }}:{{ db_port }}:{{ db_name }}:{{ db_user }}:{{ db_password }}"
        dest: /etc/skel/.pgpass
        mode: '0600'

    - name: Create preferences.xml for centralized database
      ansible.builtin.copy:
        content: |
          <?xml version="1.0" encoding="UTF-8"?>
          <preferences>
            <ResolveDatabase>
              <DatabaseType>PostgreSQL</DatabaseType>
              <DatabaseHost>{{ db_host }}</DatabaseHost>
              <DatabasePort>{{ db_port }}</DatabasePort>
              <DatabaseName>{{ db_name }}</DatabaseName>
              <DatabaseUser>{{ db_user }}</DatabaseUser>
            </ResolveDatabase>
            <ProjectLibrary>
              <ProjectPath>{{ resolve_projects_path }}</ProjectPath>
            </ProjectLibrary>
            <CacheClipsLocation>$HOME/.cache/resolve/CacheClip</CacheClipsLocation>
            <GalleryStillsLocation>$HOME/.cache/resolve/Gallery</GalleryStillsLocation>
            <ProxyMediaLocation>$HOME/.cache/resolve/Proxy</ProxyMediaLocation>
          </preferences>
        dest: /etc/skel/.local/share/DaVinciResolve/configs/preferences.xml
        mode: '0644'

    # STEP 4: Apply Configuration to Existing AD Users
    - name: Apply configuration to existing AD users
      ansible.builtin.shell: |
        for user_home in /home/ad.noxvfx.com/*; do
          if [ -d "$user_home" ]; then
            user=$(basename "$user_home")
            uid=$(id -u "$user" 2>/dev/null || echo 0)
            if [ $uid -gt 400000000 ]; then
              # Create config directory
              mkdir -p "$user_home/.local/share/DaVinciResolve/configs"
              
              # Copy preferences
              cp /etc/skel/.local/share/DaVinciResolve/configs/preferences.xml "$user_home/.local/share/DaVinciResolve/configs/"
              
              # Copy .pgpass for database authentication
              cp /etc/skel/.pgpass "$user_home/.pgpass"
              chmod 0600 "$user_home/.pgpass"
              
              # Create cache directories
              mkdir -p "$user_home/.cache/resolve/"{CacheClip,Gallery,Proxy}
              
              # Set ownership
              chown -R "$user":"domain users@ad.noxvfx.com" "$user_home/.local/share/DaVinciResolve"
              chown -R "$user":"domain users@ad.noxvfx.com" "$user_home/.cache/resolve"
              chown "$user":"domain users@ad.noxvfx.com" "$user_home/.pgpass"
            fi
          fi
        done
      args:
        executable: /bin/bash

    # Cleanup
    - name: Clean up temporary installation files
      ansible.builtin.file:
        path: "{{ resolve_temp_dir }}"
        state: absent

    - name: Display installation completion message
      ansible.builtin.debug:
        msg: 
          - "DaVinci Resolve Studio 20.2.1 installation completed!"
          - "Using CENTRALIZED PostgreSQL Database"
          - "Database Server: {{ db_host }}:{{ db_port }}"
          - "Database Name: {{ db_name }}"
          - "Shared projects: {{ resolve_projects_path }}"
          - "User cache: ~/.cache/resolve/"
          - "All workstations share the same database - full collaboration enabled!"
          - "SELinux has been configured for DaVinci Resolve"
