---
- name: Install Thinkbox Deadline 10.4.2.2 Client
  hosts: all
  become: yes
  vars:
    deadline_version: "10.4.2.2"
    deadline_installer: "DeadlineClient-{{ deadline_version }}-linux-x64-installer.run"
    deadline_install_path: "/opt/Thinkbox/Deadline10"
    deadline_repo_path: "/mnt/Library/_deadlinerepo/repository"
    rcs_server: "192.168.11.16"
    rcs_port: "4433"
    client_cert_path: "/mnt/Library/_deadlinerepo/certs/Deadline10RemoteClient.pfx"
    client_cert_password: "N0Xdeadline"
    ad_home_base: "/home/ad.noxvfx.com"
    render_user: "render"
    
  tasks:
    # STEP 1: Install Dependencies
    - name: Enable EPEL repository
      ansible.builtin.dnf:
        name:
          - epel-release
        state: present
      tags: dependencies

    - name: Enable CRB (CodeReady Builder) repository
      ansible.builtin.command:
        cmd: dnf config-manager --set-enabled crb
      args:
        creates: /etc/yum.repos.d/crb.repo
      tags: dependencies

    - name: Install required dependencies for Deadline Client
      ansible.builtin.dnf:
        name:
          - libX11
          - libXext
          - mesa-libGL
          - mesa-libGLU
          - nfs-utils
          - libxcrypt-compat
          - ncurses-compat-libs
        state: present
      tags: dependencies

    # STEP 2: Repository and Installer Setup
    - name: Check if repository is already mounted or accessible
      ansible.builtin.stat:
        path: "{{ deadline_repo_path }}"
      register: repo_check
      tags: repository

    - name: Verify repository is accessible
      ansible.builtin.command: ls {{ deadline_repo_path }}
      register: repo_access
      failed_when: repo_access.rc != 0
      changed_when: false
      tags: repository

    - name: Display repository status
      ansible.builtin.debug:
        msg: "Repository at {{ deadline_repo_path }} is accessible"
      tags: repository

    - name: Create temporary directory for installer
      ansible.builtin.file:
        path: /tmp/deadline_install
        state: directory
        mode: '0755'
      tags: installer

    - name: Copy Deadline installer to target
      ansible.builtin.copy:
        src: "../../files/{{ deadline_installer }}"
        dest: "/tmp/deadline_install/{{ deadline_installer }}"
        mode: '0755'
      tags: installer

    - name: Verify client certificate exists on repository
      ansible.builtin.stat:
        path: "{{ client_cert_path }}"
      register: cert_file
      failed_when: not cert_file.stat.exists
      tags: certificates

    # STEP 3: Silent Installation (Hybrid Mode with Render User)
    - name: Check if Deadline is already installed
      ansible.builtin.stat:
        path: "{{ deadline_install_path }}"
      register: deadline_installed
      tags: install

    - name: Install Deadline Client in silent mode (daemon with render user)
      ansible.builtin.command:
        cmd: >
          /tmp/deadline_install/{{ deadline_installer }}
          --mode unattended
          --prefix {{ deadline_install_path }}
          --connectiontype Remote
          --proxyrootdir {{ rcs_server }}:{{ rcs_port }}
          --proxycertificate {{ client_cert_path }}
          --proxycertificatepassword {{ client_cert_password }}
          --slavestartup false
          --launcherstartup true
          --launcherdaemon true
          --daemonuser {{ render_user }}
          --blockautoupdateoverride Blocked
          --installer-language en
      args:
        creates: "{{ deadline_install_path }}/bin/deadlinecommand"
      when: not deadline_installed.stat.exists
      tags: install
      register: install_result

    - name: Display installation result
      ansible.builtin.debug:
        var: install_result
      when: install_result.changed
      tags: install

    # STEP 3b: Fix existing installations - reconfigure daemon for render user
    - name: Stop Deadline launcher daemon if running
      ansible.builtin.systemd:
        name: deadline10launcher
        state: stopped
      failed_when: false
      tags: 
        - install
        - fix_daemon

    - name: Update daemon service file for render user
      ansible.builtin.lineinfile:
        path: /etc/systemd/system/deadline10launcher.service
        regexp: '^User='
        line: 'User={{ render_user }}'
      failed_when: false
      tags:
        - install
        - fix_daemon

    - name: Reload systemd after service change
      ansible.builtin.systemd:
        daemon_reload: yes
      tags:
        - install
        - fix_daemon

    - name: Enable Deadline launcher daemon
      ansible.builtin.systemd:
        name: deadline10launcher
        enabled: yes
      failed_when: false
      tags:
        - install
        - fix_daemon

    - name: Start Deadline launcher daemon
      ansible.builtin.systemd:
        name: deadline10launcher
        state: started
      failed_when: false
      tags:
        - install
        - fix_daemon

    # STEP 4: Configure Render User
    - name: Wait for render user home directory to be created
      ansible.builtin.wait_for:
        path: "{{ ad_home_base }}/{{ render_user }}"
        state: present
        timeout: 30
      tags: configure_render_user

    - name: Create .deadline directory for render user
      ansible.builtin.file:
        path: "{{ ad_home_base }}/{{ render_user }}/.deadline"
        state: directory
        owner: "{{ render_user }}"
        group: "domain users"
        mode: '0755'
      tags: configure_render_user

    - name: Configure deadline.ini for render user
      ansible.builtin.copy:
        dest: "{{ ad_home_base }}/{{ render_user }}/.deadline/deadline.ini"
        owner: "{{ render_user }}"
        group: "domain users"
        mode: '0644'
        content: |
          [ConnectionType]
          Type=Remote
          [Proxy]
          Root={{ rcs_server }}:{{ rcs_port }}
          SSLCertificate={{ client_cert_path }}
          [AutoConfiguration]
          Enabled=True
      tags: configure_render_user

    # STEP 5: Configure for Existing AD Users (Artists)
    - name: Find all existing AD user home directories
      ansible.builtin.find:
        paths: "{{ ad_home_base }}"
        file_type: directory
        recurse: no
      register: ad_user_homes_raw
      tags: configure_users

    - name: Filter only actual user directories (UID > 400000000)
      ansible.builtin.set_fact:
        ad_user_homes:
          files: "{{ ad_user_homes_raw.files | selectattr('uid', 'gt', 400000000) | list }}"
      tags: configure_users

    - name: Create .deadline directory for existing AD users
      ansible.builtin.file:
        path: "{{ item.path }}/.deadline"
        state: directory
        owner: "{{ item.path | basename }}"
        group: "{{ item.gid }}"
        mode: '0755'
      loop: "{{ ad_user_homes.files }}"
      tags: configure_users

    - name: Configure deadline.ini for existing AD users
      ansible.builtin.copy:
        dest: "{{ item.path }}/.deadline/deadline.ini"
        owner: "{{ item.path | basename }}"
        group: "{{ item.gid }}"
        mode: '0644'
        content: |
          [ConnectionType]
          Type=Remote
          [Proxy]
          Root={{ rcs_server }}:{{ rcs_port }}
          SSLCertificate={{ client_cert_path }}
          [AutoConfiguration]
          Enabled=True
      loop: "{{ ad_user_homes.files }}"
      tags: configure_users

    # STEP 6: Configure for Future AD Users (/etc/skel/)
    - name: Create .deadline directory in /etc/skel
      ansible.builtin.file:
        path: /etc/skel/.deadline
        state: directory
        mode: '0755'
      tags: configure_skel

    - name: Configure deadline.ini in /etc/skel for future users
      ansible.builtin.copy:
        dest: /etc/skel/.deadline/deadline.ini
        mode: '0644'
        content: |
          [ConnectionType]
          Type=Remote
          [Proxy]
          Root={{ rcs_server }}:{{ rcs_port }}
          SSLCertificate={{ client_cert_path }}
          [AutoConfiguration]
          Enabled=True
      tags: configure_skel

    # STEP 7: Configure Desktop Shortcuts
    - name: Create .local/share/applications directory for existing AD users
      ansible.builtin.file:
        path: "{{ item.path }}/.local/share/applications"
        state: directory
        owner: "{{ item.path | basename }}"
        group: "{{ item.gid }}"
        mode: '0755'
      loop: "{{ ad_user_homes.files }}"
      tags: desktop_shortcuts

    - name: Copy original Deadline desktop files for existing AD users
      ansible.builtin.copy:
        src: "{{ deadline_install_path }}/{{ item[1] }}"
        dest: "{{ item[0].path }}/.local/share/applications/{{ item[1] }}"
        owner: "{{ item[0].path | basename }}"
        group: "{{ item[0].gid }}"
        mode: '0644'
        remote_src: yes
      loop: "{{ ad_user_homes.files | product(['deadlinelauncher10.desktop', 'deadlinemonitor10.desktop', 'deadlineworker10.desktop']) | list }}"
      tags: desktop_shortcuts

    - name: Create .local/share/applications directory in /etc/skel
      ansible.builtin.file:
        path: /etc/skel/.local/share/applications
        state: directory
        mode: '0755'
      tags: desktop_shortcuts

    - name: Copy original Deadline desktop files to /etc/skel
      ansible.builtin.copy:
        src: "{{ deadline_install_path }}/{{ item }}"
        dest: /etc/skel/.local/share/applications/{{ item }}
        mode: '0644'
        remote_src: yes
      loop:
        - deadlinelauncher10.desktop
        - deadlinemonitor10.desktop
        - deadlineworker10.desktop
      tags: desktop_shortcuts

    # STEP 8: Configure Deadline Environment
    - name: Add Deadline to system PATH
      ansible.builtin.copy:
        dest: /etc/profile.d/deadline.sh
        mode: '0644'
        content: |
          export DEADLINE_PATH={{ deadline_install_path }}
          export PATH=$PATH:{{ deadline_install_path }}/bin
      tags: environment

    - name: Verify Deadline installation
      ansible.builtin.command: "{{ deadline_install_path }}/bin/deadlinecommand --version"
      register: deadline_version_check
      changed_when: false
      tags: verify

    - name: Display Deadline version
      ansible.builtin.debug:
        msg: "Deadline installed successfully: {{ deadline_version_check.stdout }}"
      tags: verify

    # STEP 9: Cleanup
    - name: Remove temporary installer files
      ansible.builtin.file:
        path: /tmp/deadline_install
        state: absent
      tags: cleanup

    - name: Installation complete message
      ansible.builtin.debug:
        msg: |
          Deadline {{ deadline_version }} installation completed successfully!
          - Installation path: {{ deadline_install_path }}
          - Repository: {{ deadline_repo_path }}
          - RCS Server: {{ rcs_server }}:{{ rcs_port }}
          - Mode: HYBRID (daemon running as '{{ render_user }}' user)
          - Launcher daemon auto-starts on boot
          - Worker does NOT auto-start (remotely controlled)
          - Artists can use Monitor to view farm and manage Workers
          - Scheduling available via Pulse or command line
          - Configured for existing AD users in {{ ad_home_base }}
          - Configured for future users via /etc/skel
          - Desktop shortcuts added for Launcher, Monitor, and Worker
      tags: always
