---
- name: Install Development Tools and Utilities
  hosts: all
  become: yes

  tasks:
    - name: Install additional development tools and utilities
      ansible.builtin.dnf:
        name:
          - git
          - curl
          - wget
          - tree
          - vim
          - nano
          - unzip
          - gcc
          - make
          - cmake
          - python3-pip
          - nodejs
          - npm
        state: present

    - name: Verify Git installation
      ansible.builtin.command: git --version
      register: git_version
      failed_when: false
      changed_when: false

    - name: Verify Python installation
      ansible.builtin.command: python3 --version
      register: python_version
      failed_when: false
      changed_when: false

    - name: Verify Node.js installation
      ansible.builtin.command: node --version
      register: node_version
      failed_when: false
      changed_when: false

    - name: Display development tools installation status
      ansible.builtin.debug:
        msg:
          - "{{ '✅ Git: ' + git_version.stdout if git_version.rc == 0 else '❌ Git installation failed' }}"
          - "{{ '✅ Python: ' + python_version.stdout if python_version.rc == 0 else '❌ Python installation failed' }}"
          - "{{ '✅ Node.js: ' + node_version.stdout if node_version.rc == 0 else '❌ Node.js installation failed' }}"
          - "✅ Additional tools installed: curl, wget, tree, vim, nano, unzip, gcc, make, cmake, npm"
