---
- name: Fix DCV Session Permissions and Recreation
  hosts: all
  become: yes
  
  tasks:
    - name: Stop DCV server
      ansible.builtin.systemd:
        name: dcvserver
        state: stopped

    - name: Configure DCV permissions to allow all authenticated users
      ansible.builtin.copy:
        dest: /etc/dcv/dcv_permissions.conf
        content: |
          [permissions]
          %owner% allow builtin
          %authenticated% allow builtin
        mode: '0644'

    - name: Update DCV main configuration
      ansible.builtin.copy:
        dest: /etc/dcv/dcv.conf
        content: |
          [license]
          license-file="5053@license"

          [security]
          authentication="system"

          [display]
          target-fps=30

          [display/linux]
          gl-displays=[":0.0"]
          use-glx-fallback-provider=true

          [session-management]
          create-session=true

          [session-management/defaults]
          permissions-file="/etc/dcv/dcv_permissions.conf"

          [session-management/automatic-console-session]
          owner="root"
          storage-root="/var/run/dcv/session-storage"

          [connectivity]
          enable-quic-frontend=true
        mode: '0644'

    - name: Ensure session storage directory exists
      ansible.builtin.file:
        path: /var/run/dcv/session-storage
        state: directory
        mode: '0755'
        owner: dcv
        group: dcv

    - name: Start DCV server
      ansible.builtin.systemd:
        name: dcvserver
        state: started

    - name: Wait for DCV to start
      ansible.builtin.wait_for:
        port: 8443
        delay: 5
        timeout: 60

    - name: Wait for session initialization
      ansible.builtin.pause:
        seconds: 10

    - name: Check if automatic console session was created
      ansible.builtin.command:
        cmd: dcv list-sessions
      register: auto_sessions
      changed_when: false
      failed_when: false

    - name: Display auto-created sessions
      ansible.builtin.debug:
        msg: "{{ auto_sessions.stdout_lines }}"

    - name: Manually create console session if not exists
      ansible.builtin.command:
        cmd: dcv create-session --type=console --owner root console
      when: "'console' not in auto_sessions.stdout"
      register: manual_session
      failed_when: false

    - name: Display manual session creation result
      ansible.builtin.debug:
        msg: "{{ manual_session.stdout }}"
      when: manual_session is defined and manual_session.stdout is defined

    - name: Final session list
      ansible.builtin.command:
        cmd: dcv list-sessions
      register: final_sessions
      changed_when: false

    - name: Display all active sessions
      ansible.builtin.debug:
        msg: "{{ final_sessions.stdout_lines }}"

    - name: Get console session details
      ansible.builtin.command:
        cmd: dcv describe-session console
      register: console_details
      changed_when: false
      failed_when: false

    - name: Show console session info
      ansible.builtin.debug:
        msg: "{{ console_details.stdout_lines }}"

    - name: Check DCV server status
      ansible.builtin.systemd:
        name: dcvserver
      register: dcv_status

    - name: Final summary
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - "DCV Configuration Updated"
          - "=========================================="
          - "Service Status: {{ dcv_status.status.ActiveState }}"
          - "Console Session Owner: root"
          - "All authenticated AD users can connect"
          - "Access: https://{{ inventory_hostname }}:8443"
          - "Login with your AD credentials"
          - "=========================================="
