---
- name: Fix DCV Session Creation - Reboot and Configure
  hosts: all
  become: yes
  
  tasks:
    - name: Ensure GDM (X server) starts on boot
      ansible.builtin.systemd:
        name: gdm
        state: started
        enabled: yes

    - name: Verify graphical target is set as default
      ansible.builtin.command:
        cmd: systemctl get-default
      register: default_target
      changed_when: false

    - name: Display current default target
      ansible.builtin.debug:
        msg: "Current default target: {{ default_target.stdout }}"

    - name: Check DCV configuration before reboot
      ansible.builtin.command:
        cmd: cat /etc/dcv/dcv.conf
      register: dcv_config_before
      changed_when: false

    - name: Display DCV config snippet
      ansible.builtin.debug:
        msg: "{{ dcv_config_before.stdout_lines | select('search', 'automatic-console-session') | list }}"

    - name: Reboot servers to initialize X display and DCV sessions
      ansible.builtin.reboot:
        msg: "Rebooting to initialize DCV console sessions with X server"
        reboot_timeout: 600
        
    - name: Wait for systems to come back online
      ansible.builtin.wait_for_connection:
        delay: 30
        timeout: 300

    - name: Wait for DCV server to start after reboot
      ansible.builtin.wait_for:
        port: 8443
        delay: 10
        timeout: 120

    - name: Verify DCV server is running after reboot
      ansible.builtin.systemd:
        name: dcvserver
        state: started

    - name: Wait for DCV to fully initialize sessions
      ansible.builtin.pause:
        seconds: 15

    - name: Check if X server is running
      ansible.builtin.command:
        cmd: ps aux
      register: process_list
      changed_when: false

    - name: Verify X or Xwayland process
      ansible.builtin.debug:
        msg: "{{ process_list.stdout_lines | select('search', 'X') | list }}"

    - name: List DCV sessions after reboot
      ansible.builtin.command:
        cmd: dcv list-sessions
      register: dcv_sessions
      changed_when: false
      failed_when: false

    - name: Display active DCV sessions
      ansible.builtin.debug:
        msg: "{{ dcv_sessions.stdout_lines if dcv_sessions.stdout_lines else 'No sessions found yet' }}"

    - name: Check DCV server logs for errors
      ansible.builtin.command:
        cmd: journalctl -u dcvserver -n 30 --no-pager
      register: dcv_logs
      changed_when: false

    - name: Display recent DCV logs
      ansible.builtin.debug:
        msg: "{{ dcv_logs.stdout_lines }}"

    - name: Final status summary
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - "Post-Reboot DCV Status"
          - "=========================================="
          - "DCV Service: Active"
          - "Port 8443: Open"
          - "Check sessions with: dcv list-sessions"
          - "Access via: https://{{ inventory_hostname }}:8443"
          - "=========================================="
