---
- name: Configure DCV with Correct RLM ISV Port
  hosts: all
  become: yes
  
  tasks:
    - name: Update systemd override with correct ISV port
      ansible.builtin.copy:
        dest: /etc/systemd/system/dcvserver.service.d/license.conf
        content: |
          [Service]
          Environment="RLM_LICENSE=40457@license.ad.noxvfx.com"
        mode: '0644'

    - name: Update DCV config file with ISV port
      ansible.builtin.copy:
        dest: /etc/dcv/dcv.conf
        content: |
          [license]
          license-file="40457@license.ad.noxvfx.com"

          [security]
          authentication="system"

          [display]
          target-fps=30

          [display/linux]
          gl-displays=[":0.0"]
          use-glx-fallback-provider=true

          [session-management]
          create-session=true

          [session-management/defaults]
          permissions-file="/etc/dcv/dcv_permissions.conf"

          [session-management/automatic-console-session]
          owner="root"
          storage-root="/var/run/dcv/session-storage"

          [connectivity]
          enable-quic-frontend=true
        mode: '0644'

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Restart DCV server with correct license port
      ansible.builtin.systemd:
        name: dcvserver
        state: restarted

    - name: Wait for DCV to start
      ansible.builtin.wait_for:
        port: 8443
        delay: 5
        timeout: 60

    - name: Wait for license initialization
      ansible.builtin.pause:
        seconds: 10

    - name: Create console session with working license
      ansible.builtin.shell:
        cmd: DISPLAY=:0 dcv create-session --type=console --owner root console
      register: session_create
      failed_when: false
      changed_when: false

    - name: Display session creation result
      ansible.builtin.debug:
        msg: "{{ session_create }}"

    - name: List active sessions
      ansible.builtin.command:
        cmd: dcv list-sessions
      register: sessions
      changed_when: false

    - name: Display sessions
      ansible.builtin.debug:
        msg: "{{ sessions.stdout_lines }}"

    - name: Success message
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - "DCV License Configuration FIXED!"
          - "=========================================="
          - "Using NICE ISV port: 40457"
          - "License server: license.ad.noxvfx.com"
          - "Sessions should now create successfully"
          - "=========================================="
