---
- name: Fix DCV License Server and PAM Access
  hosts: all
  become: yes
  
  tasks:
    # Fix 1: Verify license server connectivity
    - name: Test connection to license server
      ansible.builtin.command:
        cmd: nc -zv license 5053
      register: license_test
      failed_when: false
      changed_when: false

    - name: Display license server connectivity
      ansible.builtin.debug:
        msg: "{{ license_test }}"

    - name: Check if license hostname resolves
      ansible.builtin.command:
        cmd: getent hosts license
      register: license_resolve
      failed_when: false
      changed_when: false

    - name: Display license hostname resolution
      ansible.builtin.debug:
        msg: "{{ license_resolve.stdout if license_resolve.rc == 0 else 'License hostname does not resolve!' }}"

    # Fix 2: Configure PAM to allow DCV access for AD users
    - name: Create DCV PAM configuration
      ansible.builtin.copy:
        dest: /etc/pam.d/dcv
        content: |
          #%PAM-1.0
          auth       sufficient   pam_sss.so
          auth       required     pam_unix.so nullok try_first_pass
          account    sufficient   pam_sss.so
          account    required     pam_unix.so
          session    optional     pam_keyinit.so revoke
          session    required     pam_limits.so
          session    [success=1 default=ignore] pam_succeed_if.so service in crond quiet use_uid
          session    required     pam_unix.so
          session    optional     pam_sss.so
        mode: '0644'

    - name: Restart DCV server to apply PAM changes
      ansible.builtin.systemd:
        name: dcvserver
        state: restarted

    - name: Wait for DCV to restart
      ansible.builtin.wait_for:
        port: 8443
        delay: 5
        timeout: 60

    - name: Display next steps
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - "CRITICAL ISSUES FOUND:"
          - "=========================================="
          - "1. LICENSE SERVER ISSUE:"
          - "   - Cannot connect to '5053@license'"
          - "   - Error: Connection refused (-111)"
          - "   - Action: Verify RLM license server is running"
          - "   - Verify hostname 'license' resolves correctly"
          - "   - Check firewall allows port 5053"
          - ""
          - "2. PAM CONFIGURATION:"
          - "   - Fixed PAM to allow SSSD authentication"
          - "   - DCV should now accept AD user logins"
          - ""
          - "IMMEDIATE ACTION REQUIRED:"
          - "   1. Check license server status:"
          - "      ssh license 'systemctl status rlm'"
          - "   2. Verify port 5053 is open:"
          - "      telnet license 5053"
          - "   3. Check /etc/hosts or DNS for 'license'"
          - "=========================================="
