---
- name: Install GNOME Utilities
  hosts: all
  become: yes

  tasks:
    - name: Install GNOME utilities
      ansible.builtin.dnf:
        name:
          - gnome-extensions-app
          - gnome-tweaks
          - gnome-shell-extension-user-theme
          - gnome-shell-extension-dash-to-dock
          - gnome-shell-extension-desktop-icons
        state: present

    - name: Verify GNOME Extensions installation
      ansible.builtin.command: gnome-extensions --version
      register: extensions_version
      failed_when: false
      changed_when: false

    - name: Verify GNOME Tweaks installation
      ansible.builtin.command: gnome-tweaks --version
      register: tweaks_version
      failed_when: false
      changed_when: false

    - name: Display GNOME utilities installation status
      ansible.builtin.debug:
        msg:
          - "{{ '✅ GNOME Extensions installed' if extensions_version.rc == 0 else '❌ GNOME Extensions installation failed' }}"
          - "{{ '✅ GNOME Tweaks installed' if tweaks_version.rc == 0 else '❌ GNOME Tweaks installation failed' }}"
          - "✅ GNOME Shell extensions installed: user-theme, dash-to-dock, desktop-icons"
