---
# Install Krita from RPM with Flatpak fallback
- name: Install Krita
  hosts: all
  become: yes
  vars:
    krita_rpm_file: "vfx/krita-5.x.x.rpm"
    
  tasks:
    - name: Check if Krita RPM exists
      ansible.builtin.stat:
        path: "{{ krita_rpm_file }}"
      register: krita_rpm_check
      delegate_to: localhost
      become: no

    - name: Install Krita from RPM (if available)
      block:
        - name: Copy Krita RPM to target machine
          ansible.builtin.copy:
            src: "{{ krita_rpm_file }}"
            dest: "/tmp/krita.rpm"
            mode: '0644'

        - name: Install Krita from RPM
          ansible.builtin.dnf:
            name: "/tmp/krita.rpm"
            state: present
            disable_gpg_check: yes
          register: krita_rpm_install

        - name: Clean up temporary RPM file
          ansible.builtin.file:
            path: "/tmp/krita.rpm"
            state: absent

        - name: Verify Krita RPM installation
          ansible.builtin.command: krita --version
          register: krita_version
          changed_when: false

        - name: Display Krita version (RPM)
          ansible.builtin.debug:
            msg: "✅ Krita installed from RPM: {{ krita_version.stdout_lines[0] }}"

      when: krita_rpm_check.stat.exists
      rescue:
        - name: RPM installation failed, will try Flatpak
          ansible.builtin.debug:
            msg: "⚠️  Krita RPM installation failed, falling back to Flatpak"

    - name: Install Krita via Flatpak (fallback or if no RPM)
      block:
        - name: Ensure Flatpak is installed
          ansible.builtin.dnf:
            name: flatpak
            state: present

        - name: Add Flathub repository
          ansible.builtin.flatpak_remote:
            name: flathub
            state: present
            flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

        - name: Install Krita via Flatpak
          ansible.builtin.flatpak:
            name: org.kde.krita
            state: present

        - name: Display Krita Flatpak installation
          ansible.builtin.debug:
            msg: "✅ Krita installed via Flatpak"

      when: not krita_rpm_check.stat.exists or krita_rpm_install is failed

    - name: Create Krita project templates directory
      ansible.builtin.file:
        path: /usr/share/krita/templates/nox
        state: directory
        mode: '0755'
      ignore_errors: yes

    - name: Display Krita installation complete
      ansible.builtin.debug:
        msg: |
          🎨 Krita installation completed!
          
          Usage tips for VFX work:
          • Set up custom brushes for concept art
          • Configure timeline for 2D animation
          • Use reference images with PureRef integration
          • Export formats: EXR, PNG sequences for compositing
