---
- name: Deploy Autodesk RV to Rocky Linux 9
  hosts: all
  become: yes
  vars:
    rv_source_zip: "../../files/RV-Linux-Rocky9-Release-2025.0.0.zip"
    rv_install_path: "/opt/RV"
  
  tasks:
    - name: Ensure unzip is installed
      dnf:
        name: unzip
        state: present

    - name: Create RV installation directory
      file:
        path: "{{ rv_install_path }}"
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Copy RV zip file to target machine
      copy:
        src: "{{ rv_source_zip }}"
        dest: "/tmp/RV-Linux-Rocky9-Release-2025.0.0.zip"
        mode: '0644'

    - name: Extract RV zip file to temp directory
      unarchive:
        src: "/tmp/RV-Linux-Rocky9-Release-2025.0.0.zip"
        dest: "/tmp/"
        remote_src: yes

    - name: Check extracted structure
      find:
        paths: "/tmp/RV-Linux-Rocky9-Release-2025.0.0"
        file_type: any
        recurse: no
      register: extracted_contents

    - name: Display extracted structure
      debug:
        msg: "{{ extracted_contents.files | map(attribute='path') | list }}"

    - name: Find RV directory with bin folder
      find:
        paths: "/tmp/RV-Linux-Rocky9-Release-2025.0.0"
        file_type: directory
        patterns: "*"
        recurse: yes
      register: all_dirs

    - name: Check for bin directory
      stat:
        path: "{{ item.path }}/bin"
      loop: "{{ all_dirs.files }}"
      register: bin_checks

    - name: Identify RV root directory
      set_fact:
        rv_root: "{{ item.item.path }}"
      when: item.stat.exists
      loop: "{{ bin_checks.results }}"
      loop_control:
        label: "{{ item.item.path }}"

    - name: Copy RV contents to /opt/RV
      shell: "cp -r {{ rv_root }}/* {{ rv_install_path }}/"
      when: rv_root is defined

    - name: Set proper permissions on RV directory
      file:
        path: "{{ rv_install_path }}"
        state: directory
        recurse: yes
        mode: 'u=rwX,g=rX,o=rX'
        owner: root
        group: root

    - name: Ensure RV binaries are executable
      file:
        path: "{{ rv_install_path }}/bin"
        state: directory
        recurse: yes
        mode: 'u=rwx,g=rx,o=rx'

    - name: Create RV environment setup script
      copy:
        dest: /etc/profile.d/rv.sh
        mode: '0755'
        content: |
          #!/bin/bash
          # Autodesk RV Environment Setup
          
          export RV_HOME=/opt/RV
          export PATH=$RV_HOME/bin:$PATH
          export LD_LIBRARY_PATH=$RV_HOME/lib:$LD_LIBRARY_PATH

    - name: Clean up temporary files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/tmp/RV-Linux-Rocky9-Release-2025.0.0.zip"
        - "/tmp/RV-Linux-Rocky9-Release-2025.0.0"

    - name: Verify RV installation
      stat:
        path: "{{ rv_install_path }}/bin/rv"
      register: rv_binary

    - name: Display installation status
      debug:
        msg: "RV binary exists: {{ rv_binary.stat.exists }}"
    
    - name: Create RV desktop entry for all users
          copy:
            dest: /usr/share/applications/autodesk-rv.desktop
            mode: '0644'
            content: |
              [Desktop Entry]
              Version=1.0
              Type=Application
              Name=Autodesk RV
              Comment=Media review and playback software
              Exec=/opt/RV/bin/rv
              Icon=/opt/RV/resources/rv.png
              Terminal=false
              Categories=Graphics;Video;AudioVideo;
              StartupNotify=true
    
        - name: Update desktop database
          command: update-desktop-database /usr/share/applications/
          changed_when: false
