---
# Install Visual Studio Code from official repository
- name: Install Visual Studio Code
  hosts: all
  become: yes
    
  tasks:
    - name: Import Microsoft GPG key
      ansible.builtin.rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc

    - name: Add Visual Studio Code repository
      ansible.builtin.yum_repository:
        name: vscode
        description: Visual Studio Code
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        gpgcheck: yes
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        enabled: yes

    - name: Install Visual Studio Code
      ansible.builtin.dnf:
        name: code
        state: present

    - name: Verify VS Code installation
      ansible.builtin.command:
        cmd: code --version
      register: vscode_version
      changed_when: false

    - name: Display VS Code version
      ansible.builtin.debug:
        msg: "✅ VS Code installed: {{ vscode_version.stdout_lines[0] }}"
