---
# NOX VFX GNOME Configuration - Dark Theme and VFX Optimizations
- name: Configure GNOME for NOX VFX Workstations
  hosts: all
  become: yes
  gather_facts: yes
  
  vars:
    # GNOME theme configuration
    enable_dark_theme: true
    install_extensions: true
    # configure_favorites: true
    optimize_for_vfx: true
    
    # GNOME favorites (includes all NOX VFX software)
    # gnome_favorites:
    #   - 'org.gnome.Nautilus.desktop'          # File Manager
    #   - 'google-chrome.desktop'               # Google Chrome
    #   - 'com.slack.Slack.desktop'             # Slack
    #   - 'code.desktop'                        # VS Code
    #   - 'sublime_text.desktop'                # Sublime Text
    #   - 'org.kde.krita.desktop'               # Krita
    #   - 'org.blender.Blender.desktop'         # Blender
    #   - 'pureref.desktop'                     # PureRef
    #   - 'org.gnome.Extensions.desktop'        # GNOME Extensions
    #   - 'org.gnome.tweaks.desktop'            # GNOME Tweaks

  tasks:
    - name: Display GNOME configuration plan
      ansible.builtin.debug:
        msg: |
          🖥️ NOX VFX GNOME Configuration
          
          Target: {{ inventory_hostname }}
          
          🎨 Configuration:
          • Dark Theme: {{ 'Yes' if enable_dark_theme else 'No' }}
          • Extensions: {{ 'Yes' if install_extensions else 'No' }}
          • Favorites: {{ 'Yes' if configure_favorites else 'No' }}
          • VFX Optimizations: {{ 'Yes' if optimize_for_vfx else 'No' }}
          
          🎯 This will create a professional, VFX-optimized desktop environment

    # ====== GNOME EXTENSIONS INSTALLATION ======
    - name: Install GNOME extensions and tools
      ansible.builtin.dnf:
        name:
          - gnome-extensions-app
          - gnome-tweaks
          - gnome-shell-extension-user-theme
          - gnome-shell-extension-dash-to-dock
          - gnome-shell-extension-desktop-icons
        state: present
      when: install_extensions | default(true)

    # ====== SYSTEM-WIDE DCONF CONFIGURATION ======
    - name: Create dconf system database directory
      ansible.builtin.file:
        path: /etc/dconf/db/local.d
        state: directory
        mode: '0755'

    - name: Create dconf user profile
      ansible.builtin.copy:
        content: |
          user-db:user
          system-db:local
        dest: /etc/dconf/profile/user
        mode: '0644'

    - name: Configure system-wide GNOME dark theme and settings
      ansible.builtin.copy:
        content: |
          # NOX VFX GNOME Configuration
          
          # Dark theme settings
          [org/gnome/desktop/interface]
          gtk-theme='Adwaita-dark'
          color-scheme='prefer-dark'
          show-battery-percentage=true
          clock-show-weekday=true
          clock-show-seconds=false
          enable-hot-corners=false
          
          # Window manager settings
          [org/gnome/desktop/wm/preferences]
          button-layout='appmenu:minimize,maximize,close'
          theme='Adwaita-dark'
          
          # File manager settings for VFX workflow
          [org/gtk/settings/file-chooser]
          show-hidden=false
          show-size-column=true
          show-type-column=true
          sort-directories-first=true
          
          # Power settings for VFX workstations
          [org/gnome/settings-daemon/plugins/power]
          sleep-inactive-ac-type='nothing'
          sleep-inactive-battery-type='suspend'
          
          # GNOME Shell extensions configuration
          [org/gnome/shell]
          enabled-extensions=['dash-to-dock@micxgx.gmail.com', 'user-theme@gnome-shell-extensions.gcampax.github.com', 'desktop-icons@csoriano']
          # favorite-apps={{ gnome_favorites | to_json }}
          
          # Dash to Dock extension settings
          [org/gnome/shell/extensions/dash-to-dock]
          dock-position='BOTTOM'
          dock-fixed=false
          autohide=true
          intellihide=true
          extend-height=false
          show-trash=true
          show-mounts=true
          transparency-mode='FIXED'
          background-opacity=0.8
          
          # Terminal settings (dark theme)
          [org/gnome/terminal/legacy/profiles:]
          default='{{ ansible_hostname }}-profile'
          list=['{{ ansible_hostname }}-profile']
          
          [org/gnome/terminal/legacy/profiles:/:{{ ansible_hostname }}-profile]
          visible-name='NOX VFX Terminal'
          use-theme-colors=false
          background-color='rgb(23,20,33)'
          foreground-color='rgb(208,207,204)'
          use-transparent-background=false
          
          # Nautilus (file manager) optimizations
          [org/gnome/nautilus/preferences]
          default-folder-viewer='list-view'
          search-filter-time-type='last_modified'
          show-create-link=true
          show-delete-permanently=true
          
          # VFX-specific optimizations
          [org/gnome/mutter]
          experimental-features=['scale-monitor-framebuffer']
          
        dest: /etc/dconf/db/local.d/01-nox-gnome-config
        mode: '0644'
      notify: update dconf

    # ====== USER SESSION SCRIPTS ======
    - name: Create GNOME theme and configuration script for user sessions
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          # NOX VFX GNOME Theme and Configuration Script
          
          # Wait for GNOME session to be ready
          sleep 15
          
          # Set up environment
          if [ -z "$DISPLAY" ]; then export DISPLAY=:0; fi
          if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
              export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u)/bus"
          fi
          
          # Wait for gsettings and GNOME Shell to be available
          timeout=60
          while [ $timeout -gt 0 ]; do
              if gsettings list-schemas | grep -q "org.gnome.desktop.interface" && pgrep -x gnome-shell > /dev/null; then
                  break
              fi
              sleep 2
              ((timeout--))
          done
          
          echo "Configuring NOX VFX GNOME environment for user $(whoami)..."
          
          # Dark theme
          gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark' 2>/dev/null || true
          gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark' 2>/dev/null || true
          
          # Interface settings
          gsettings set org.gnome.desktop.interface show-battery-percentage true 2>/dev/null || true
          gsettings set org.gnome.desktop.interface clock-show-weekday true 2>/dev/null || true
          gsettings set org.gnome.desktop.interface clock-show-seconds false 2>/dev/null || true
          gsettings set org.gnome.desktop.interface enable-hot-corners false 2>/dev/null || true
          
          # Window manager
          gsettings set org.gnome.desktop.wm.preferences button-layout 'appmenu:minimize,maximize,close' 2>/dev/null || true
          gsettings set org.gnome.desktop.wm.preferences theme 'Adwaita-dark' 2>/dev/null || true
          
          # File manager
          gsettings set org.gtk.settings.file-chooser show-hidden false 2>/dev/null || true
          gsettings set org.gtk.settings.file-chooser show-size-column true 2>/dev/null || true
          gsettings set org.gtk.settings.file-chooser show-type-column true 2>/dev/null || true
          gsettings set org.gtk.settings.file-chooser sort-directories-first true 2>/dev/null || true
          
          # Power settings
          gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing' 2>/dev/null || true
          
          # Enable extensions
          gsettings set org.gnome.shell enabled-extensions "['dash-to-dock@micxgx.gmail.com', 'user-theme@gnome-shell-extensions.gcampax.github.com', 'desktop-icons@csoriano']" 2>/dev/null || true
          
          # Configure Dash to Dock
          gsettings set org.gnome.shell.extensions.dash-to-dock dock-position 'BOTTOM' 2>/dev/null || true
          gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed false 2>/dev/null || true
          gsettings set org.gnome.shell.extensions.dash-to-dock autohide true 2>/dev/null || true
          gsettings set org.gnome.shell.extensions.dash-to-dock intellihide true 2>/dev/null || true
          gsettings set org.gnome.shell.extensions.dash-to-dock extend-height false 2>/dev/null || true
          gsettings set org.gnome.shell.extensions.dash-to-dock show-trash true 2>/dev/null || true
          gsettings set org.gnome.shell.extensions.dash-to-dock show-mounts true 2>/dev/null || true
          
          # Set favorites
          # gsettings set org.gnome.shell favorite-apps '{{ gnome_favorites | to_json }}' 2>/dev/null || true
          
          # Terminal theme
          profile_id=$(gsettings get org.gnome.Terminal.ProfilesList default 2>/dev/null | tr -d "'")
          if [ -n "$profile_id" ]; then
              gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$profile_id/ use-theme-colors false 2>/dev/null || true
              gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$profile_id/ background-color 'rgb(23,20,33)' 2>/dev/null || true
              gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$profile_id/ foreground-color 'rgb(208,207,204)' 2>/dev/null || true
          fi
          
          logger "NOX VFX GNOME configuration applied for user $(whoami)"
          echo "GNOME configuration completed for user $(whoami)"
        dest: /usr/local/bin/set-nox-gnome-config.sh
        mode: '0755'

    # ====== AUTOSTART CONFIGURATION ======
    - name: Create autostart directory
      ansible.builtin.file:
        path: /etc/xdg/autostart
        state: directory
        mode: '0755'

    - name: Create autostart entry for GNOME configuration
      ansible.builtin.copy:
        content: |
          [Desktop Entry]
          Type=Application
          Name=NOX GNOME Configuration
          Comment=Apply NOX VFX GNOME theme and settings
          Exec=/usr/local/bin/set-nox-gnome-config.sh
          Hidden=false
          NoDisplay=true
          X-GNOME-Autostart-enabled=true
          X-GNOME-Autostart-Delay=20
          Categories=System;Settings;
          StartupNotify=false
        dest: /etc/xdg/autostart/nox-gnome-config.desktop
        mode: '0644'

    - name: Add GNOME configuration to system profile
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          # Apply NOX VFX GNOME configuration for GNOME sessions
          if [ "$XDG_CURRENT_DESKTOP" = "GNOME" ] && [ -n "$DISPLAY" ]; then
              # Run in background with delay to ensure GNOME Shell is ready
              (sleep 25 && /usr/local/bin/set-nox-gnome-config.sh &) 2>/dev/null
          fi
        dest: /etc/profile.d/Z97-nox-gnome-config.sh
        mode: '0755'

    # ====== IMMEDIATE APPLICATION FOR LOGGED-IN USERS ======
    - name: Apply GNOME configuration to currently logged-in users
      ansible.builtin.shell: |
        for user in $(ps aux | grep -v grep | grep gnome-shell | awk '{print $1}' | sort | uniq); do
          if [ -n "$user" ] && [ "$user" != "gdm" ]; then
            user_id=$(id -u "$user" 2>/dev/null)
            if [ -n "$user_id" ] && [ -S "/run/user/$user_id/bus" ]; then
              echo "Applying NOX GNOME configuration for logged-in user: $user"
              
              # Apply dark theme
              sudo -u "$user" DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$user_id/bus" \
                gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark' 2>/dev/null || true
              sudo -u "$user" DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$user_id/bus" \
                gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark' 2>/dev/null || true
              
              # Apply favorites
              sudo -u "$user" DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$user_id/bus" \
                # gsettings set org.gnome.shell favorite-apps '{{ gnome_favorites | to_json }}' 2>/dev/null || true
              
              # Apply interface settings
              sudo -u "$user" DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$user_id/bus" \
                gsettings set org.gnome.desktop.interface show-battery-percentage true 2>/dev/null || true
              sudo -u "$user" DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$user_id/bus" \
                gsettings set org.gnome.desktop.interface enable-hot-corners false 2>/dev/null || true
              
              echo "Configuration applied for user: $user"
            fi
          fi
        done
      ignore_errors: yes

    # ====== VERIFICATION ======
    - name: Create GNOME configuration verification script
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          echo "=== NOX VFX GNOME Configuration Verification ==="
          echo
          
          if [ "$XDG_CURRENT_DESKTOP" != "GNOME" ]; then
              echo "❌ Not in GNOME session"
              echo "   Please run this from a GNOME desktop environment"
              exit 1
          fi
          
          echo "🖥️ GNOME Environment:"
          echo "   Session: $XDG_SESSION_TYPE"
          echo "   Desktop: $XDG_CURRENT_DESKTOP"
          echo
          
          echo "🎨 Theme Configuration:"
          theme=$(gsettings get org.gnome.desktop.interface gtk-theme 2>/dev/null)
          color_scheme=$(gsettings get org.gnome.desktop.interface color-scheme 2>/dev/null)
          echo "   Theme: $theme"
          echo "   Color Scheme: $color_scheme"
          
          if [[ "$theme" == *"dark"* ]] && [[ "$color_scheme" == *"dark"* ]]; then
              echo "   ✅ Dark theme active"
          else
              echo "   ⚠️ Dark theme may not be active"
          fi
          echo
          
          echo "📌 Favorites:"
          favorites=$(gsettings get org.gnome.shell favorite-apps 2>/dev/null)
          if [[ "$favorites" == *"chrome"* ]] && [[ "$favorites" == *"krita"* ]]; then
              echo "   ✅ NOX favorites configured"
          else
              echo "   ⚠️ Favorites may need attention"
          fi
          echo
          
          echo "🔧 Extensions:"
          enabled_extensions=$(gsettings get org.gnome.shell enabled-extensions 2>/dev/null)
          if [[ "$enabled_extensions" == *"dash-to-dock"* ]]; then
              echo "   ✅ Dash to Dock enabled"
          else
              echo "   ⚠️ Extensions may need attention"
          fi
          echo
          
          echo "⚡ Interface Settings:"
          battery=$(gsettings get org.gnome.desktop.interface show-battery-percentage 2>/dev/null)
          hot_corners=$(gsettings get org.gnome.desktop.interface enable-hot-corners 2>/dev/null)
          echo "   Battery percentage: $battery"
          echo "   Hot corners: $hot_corners"
          echo
          
          echo "🎯 NOX VFX GNOME Configuration: Ready for VFX Work!"
        dest: /usr/local/bin/verify-nox-gnome.sh
        mode: '0755'

    - name: Display GNOME configuration completion
      ansible.builtin.debug:
        msg: |
          🎨 NOX VFX GNOME Configuration Complete!
          
          ✅ Applied Settings:
          • Dark theme (Adwaita-dark)
          • VFX-optimized interface
          • Professional favorites bar
          • Dash-to-dock with autohide
          • Power settings for workstations
          • File manager optimizations
          
          🔧 Extensions Enabled:
          • Dash to Dock
          • User Theme
          • Desktop Icons
          
          📋 Verification:
          Run as user: /usr/local/bin/verify-nox-gnome.sh
          
          🔄 Changes take effect:
          • Immediately for logged-in users
          • At next login for new sessions
          • After GNOME Shell restart (Alt+F2, type 'r')

  handlers:
    - name: update dconf
      ansible.builtin.command: dconf update
      changed_when: true
